SELECT EMPNO, ENAME, JOB, SAL,
		CASE
			WHEN job = 'MANAGER' THEN SAL * 1.1
			WHEN job = 'SALESMAN' THEN SAL * 1.05
			WHEN job = 'ANALYST' THEN SAL
			ELSE SAL * 1.03
		END AS [UPSAL]
FROM hr.emp