USE tempdb;
DROP TABLE ##TEMPTB
GO
DROP PROC Sale_RANK
GO
CREATE TABLE ##TEMPTB
(부서코드 CHAR(2),
 [매출 수량] INT)
GO
INSERT INTO ##TEMPTB VALUES('C', 50);
INSERT INTO ##TEMPTB VALUES('E', 85);
INSERT INTO ##TEMPTB VALUES('A', 100);
INSERT INTO ##TEMPTB VALUES('D', 70);
INSERT INTO ##TEMPTB VALUES('B', 70);
GO
CREATE PROC Sale_RANK
AS
SELECT 부서코드, [매출 수량], DENSE_RANK() OVER(ORDER BY [매출 수량] DESC)[매출 순위] FROM ##TEMPTB ORDER BY [매출 순위];
GO

EXEC Sale_RANK